# Scalaスケーラブルプログラミング 第32章
[全体目次へ戻る](index.md)

## 32章 フューチャーと並行処理
Javaの共有メモリとロックを中心とする並行処理モデルでは、コーディングが非常に難しい。Scalaでは、`Future`によってイミュータブルな値の非同期な変換をモデリングすることで、この難しさを解決している。計算を実行するスレッドは、暗黙の値として提供される実行コンテキストによって決まる。

### 非同期実行とTry
- `Future`オブジェクトは、別のスレッドで非同期に実行される計算を表す
- 暗黙の **実行コンテキスト** によって、非同期の計算がどんな環境で実行されるかを指定する
- `isCompleted`メソッドは非同期の計算が完了したかどうかを返す
- `value`メソッドは、**計算の成否を含めた** 結果を`Option`に包まれた`Try`として返す
  + `Try`は`Success`か`Failure`のどちらかをとるデータ型で、`try-catch`と同等の機能を提供する
  + 計算が完了していなければ`None`
  + 計算が完了している場合は、以下のどちらかを含む`Some`
    * 成功ならば、計算結果を格納した`Success`
    * 失敗ならば(途中で例外が発生した場合は)、発生した例外を格納した`Failure`


```scala
// 実行コンテキストはExcecutionContext型の値
// global実行コンテキストでは、プログラム全体で共有されるスレッドプールで非同期実行を行う
import scala.concurrent.ExcecutionContext.Implicits.global
// 10秒後に計算結果が得られる計算。これは別スレッドで実行されるので、ブロックすることはない
val fut: Future[Int] = Future { Thread.sleep(10000); 21 + 21 }
fut.value // => None
// 10秒後...
fut.value // => Some(Success(42))

// 例外を投げる非同期計算
val fut: Future[Int] = Future { Thread.sleep(10000); 21 / 0 }
// 10秒後...
fut.value // => Some(Failure(java.lang.ArithmeticException: / by zero))
```

### Futureの操作
#### 変換
- `map`や`flatMap`のような、`Future`の結果を変換するメソッドが提供されている
  + よって、for式でも利用できる

```scala
val fut = Future { Thread.sleep(10000); 21 + 21 }
// futの結果が得られたら、それに1を加える
val result: Future[Int] = fut.map(x => x + 1)

val fut1 = Future { Thread.sleep(10000); 21 + 21 }
val fut2 = Future { Thread.sleep(10000); 23 + 23 }
// 2つのFutureの結果を非同期に加算する新しいFuture
val combined = for {
  x <- fut1
  y <- fut2
} yield x + y

// for式の中でFutureを生成すると、それらは直列に実行されてしまうので注意
```

#### 作成
- `apply`の他にも、すでに完了した`Future`を作成するためのファクトリーメソッドが提供されている
  + `successful(v)`: すでに成功した`Future`
  + `falied(e)`: すでに失敗した`Future`
  + `fromTry(t)`: `Try`から、すでに完了した`Future`を生成

- `Promise`: ある`Future`の結果を制御するオブジェクト
  + `Promise`が完了したとき、紐付いた`Future`も完了する

```scala
val pro = Promise[Int]
val fut = pro.future // => Future[Int] = ...
fut.value // => None

// successメソッドは、Promiseを成功裏に完了させる
// 紐付いたFutureも同時に完了する
pro.success(42)
fut.value // => Some(Success(42))

// 他にも渡された例外によって失敗するfailureや、Tryの結果に応じて成否が変わるcomplete、
// Futureを受け取り、その結果に応じて成否が変わるcompleteWithがある
```

#### フィルタリング
- 結果の値がある性質を満たしているかをチェックする`filter`メソッドや、性質を満たしていることを確認した上で変換する`collect`メソッドがある
  + 性質を満たしていない場合、結果は`NoSuchElementException`を含む失敗となる

```scala
val fut = Future(42)
fut.filter(_ > 0).value // => Some(Success(42))
fut.filter(_ < 0).value // => Some(Failure(...))

// withFilterもあるのでfor式でガードを利用できる
for(res <- fut if res > 0) yield res

// Futureの結果が、渡された部分関数の定義域に含まれている場合のみ、その関数を適用する
val valid = fut.collect{ case res if res > 0 => res + 46 }
```

#### 失敗の処理
- `failed`: 失敗した`Future`を、成功した`Future[Throwable]`に変換する。`Future`が成功した場合は逆に失敗する
- `fallbackTo(f: Future)`: レシーバの`Future`が失敗した場合は、代わりに引数に指定した`Future`の結果を返すようにする
  + 引数の`Future`が失敗した場合、その失敗の内容は取得できない
- `recover(f: Throwable => A)`: レシーバの`Future`が失敗した場合、その例外の内容に応じた「デフォルト値」を返す`Future`に変換する
  + `recoverWith`は、デフォルト値を`Future`として与える点を除いて`recover`と同じ働きをする

```scala
val fut = { 42 / 0 }
fut.recover {
  // ArithmeticExceptionによって失敗した場合はデフォルト値-1を返す
  case ex: ArithmeticException => -1
}
fut.recoverWith {
  case ex: ArithmeticException => Future { 42 + 46 }
}
```

#### 両方の場合への変換
- `transform`は、成功時と失敗時それぞれの変換を指定できる

```scala
val fut = Future(42).transform(
  res => res * -1,  // 第1引数: 成功時の変換
  ex => new Exception("see cause", ex)  // 第2引数: 失敗時の変換
)
```

#### 結合
- `zip`は、2つの成功した`Future`の結果を結合してタプルの形で返す新しい`Future`を返す
  + どちらかが失敗すると、返される`Future`はその失敗と同じ例外とともに失敗する
  + 両方失敗した場合はレシーバ側の例外が報告される
- `Future.fold`: 初期値と集約関数をとり、コレクションに含まれる`Future`の結果を集約する。最終結果は次のようになる
  + 全てが成功した場合は、各結果を指定した関数で畳み込みんだ結果とともに成功する`Future`
  + どれか1つでも失敗した場合は、一番最初に発生した例外とともに失敗する`Future`
  + `Future.reduce`は、コレクションの一番最初の`Future`を初期値とする`fold`
- `Future.sequence`: フューチャーを含むコレクション`C[Future[A]]`を`Future[C[A]]`に変換する
  + コレクションの要素の`Future`が全て成功したら、各結果を元のコレクション型に格納した結果とともに成功する`Future`を返す
  + `Future.traverse`は、`A`型の値を`Future[A]`に変換する関数にしたがってコレクション`C[A]`を`C[Future[A]]`に変換してから、`sequence`と同様の処理を行う

#### 副作用の実行
- `foreach`: `Future`が成功裏に完了したとき、副作用を実行する
- `onComplete`: `Future`が完了したとき、`Try`を引数に取るコールバック関数を実行する
  + コールバックの実行順序に一切保証はない
- `andThen`: 「元の`Future`が完了したとき、コールバックを実行する」ような`Future`を返す
  + 前のコールバックが完了しないと次のコールバックは実行されないので、コールバックの実行順序を強制できる

#### Scala2.12で追加されたメソッド
- `flatten`: ネストした`Future`を平らにする(`Future[Future[A]]`を`Future[A]`に変換する)
- `zipWith`: 「`zip`して`map`する」操作を1操作を1ステップで行う
- `transformWith`: `Try`を`Future`に変換する関数によって`Future`を変換する

### テストとFuture
- テスト時のように、`Future`の結果が出るまでブロックしたいこともある。そのために`Await.result(Future, Duration)`メソッドが用意されている。これは`Future`の結果を`Duration`で指定した時間だけ待つ。
- ScalaTest3.0では、`Future`の完了を待たずにテストを行う仕組みが追加された

***

[前へ](c31.md) /
[全体目次へ戻る](index.md) /
[次へ](c33.md)
